package com.blackwolves.mail.yahoo;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * @author gastondapice
 *
 */
public class YahooProcessor {

	private static Logger logger = LoggerFactory.getLogger(YahooProcessor.class);

	public static void main(String[] args) {
		/*
		 * FOR PRODUCTION THIS VALUES MUST BE IN false
		 */
		boolean test = false;
		boolean warmup = false;

		if(args[0] != null && args[0].equals("send")){
			logger.info("SEND ----- generate and drop bodies option selected");
			generateDropBodies(test, args);
		}else if(args[0] != null && args[0].equals("download")){
			logger.info("DOWNLOAD ----- read and tune bodies option selected");
			readAndTuneBodies(test, warmup, args);
		}else{
			logger.info("Not valid option selected, try again");
		}
	}

	/**
	 * @param test
	 * @param warmup
	 * @param args
	 */
	private static void readAndTuneBodies(boolean test, boolean warmup, String[] args) {
		if (test) {
			logger.info("TEST MODE");

			WolfYahoo handler = new TestWolfYahoo();
			handler.readEmailsAndGenerateBodies(null, null ,null);
		} else if (warmup) {
			logger.info("WARMUP MODE");
			String offer = args[1];
			String seed = args[2];
			String pass = args[3];
			WolfYahoo handler = new WarmupWolfYahoo();
			handler.readEmailsAndGenerateBodies(offer, seed, pass);
		} else {
			logger.info("ELSE MODE");
			String offer = args[1];
			String seed = args[2];
			String pass = args[3];
			WolfYahoo handler = new ProductionWolfYahoo();
			handler.readEmailsAndGenerateBodies(offer, seed, pass);
		}

	}

	/**
	 * @param test
	 * 
	 */
	private static void generateDropBodies(boolean test, String[] args) {

		// TEST PURPOSES
		// user = "edubartolini@yahoo.com";
		// pass = "Eduardito01";

		// List<String[]> contacts =
		// WolfYahoo.generateList("/Users/danigrane/Downloads/Madrivo/seeds/",
		// "mini_zebra.csv");
		// List<String[]> seeds =
		// WolfYahoo.generateList("/Users/danigrane/Downloads/Madrivo/seeds/",
		// "seeds_good.csv");
		
		String senderEmail = args[1].split(",")[0];
		String senderPassword = args[1].split(",")[1];
		String senderDomainRo = args[1].split(",")[2];
		String contactEmail = args[2];
		
//		String[] offerFroms = { "The Zebra" };
		
//		String[] offerFroms = { "Military.com" };
		
		String[] offerFroms = { "The Cool Info" };

//		String[] subjects = { "Pay as little as $27/mo for car insurance",
//				"Auto Insurance for as low as $27/mo",
//				"Car Insurance for as low as $27/mo",
//				"Car Insurance for as low as $7/week",
//				"Auto Insurance for as low as $7/wk",
//				"Time to save on your car insurance rates?",
//				"Compare Car Insurance in Real Time",
//				"Time to re-shop your car insurance rates",
//				"You're eligible to save on car insurance" };
		
//		String[] subjects = { "Veterans Don't Need 20% Down",
//				"Get up to $417k through your VA Home Loan",
//				"Lock in a Low Rate with your VA Loan",
//				"Buy a Home - $0 Down Secure Your VA Loan Today",
//				"Use Your VA Loan Benefit   $0 Down and Get up to $417k",
//				"VA Loan  Receive FREE no  obligation rate quotes",
//				"VA Loan - $0 Down and secure your loan today!" };
		
//		String[] subjects = { "Get up to $417k through your VA Home Loan" };
		
		String[] subjects = { "Obama: No comment on Clinton and trade - and other 2016 issues"};

//		String body = "<html><body bgcolor=\"#FFFFFF\"><br /><h1><center><a target=\"_blank\" href=\"http://img.betoacostadalefuncionanamelamily.ro/ecb85094cae9f7db3dd1bf283f2406e7dc3f1d2712face818a03b4438348ac85d4cc555e66b25add937ef7434cee36f6\"><font color=\"#FF0000\">\"><ont></a></center></h1><br /><map name=\"tfmeb\"><area shape=\"rect\" coords=\"4,1,2213,2551\" target=\"_blank\" href=\"http://img.betoacostadalefuncionanamelamily.ro/ecb85094cae9f7db3dd1bf283f2406e7dc3f1d2712face818a03b4438348ac85d4cc555e66b25add937ef7434cee36f6\"></map><map name=\"eknww\"><area shape=\"rect\" coords=\"2,2,2327,2317\" target=\"_blank\" href=\"http://img.betoacostadalefuncionanamelamily.ro/93cc8d0d56a0e104722e4740e4b03c529efb5b0a385359af8cf3ad376ed734d70c9f8eec2852481f76998d1f0ef9dae2\"></map><table height=\"384\" width=\"446\" align=\"center\" border=\"0\" bgcolor=\"#2E9AFE\" cellspacing=\"0\" cellpadding=\"0\"><tr><td bgcolor=\"#FFFFFF\" align=\"center\" ><p>Please click the \"Show Images\" button above if you cannot see the content.</p></td></tr><tr><td align=\"center\"><img style=\"display:block\" alt=\"content\" title=\"content\" src=\"http://img.betoacostadalefuncionanamelamily.ro/620daa263754bd3ac41416f46c330671102826c866e77945c9bb4c20c0f23e5b1701964e2ef93e023332b0d4c698012c\" usemap=\"#tfmeb\"></td></tr><tr><td align=\"center\"><img style=\"display:block\" alt=\"optout\" title=\"optout\" src=\"http://img.betoacostadalefuncionanamelamily.ro/36f64d8b1a3f59494a4a4451613eaef706cdb838fb21885edbcd93a1781226a4993d6776d1324891dd7afbe685f612d7\" usemap=\"#eknww\"></td></tr></table><br /></body></html>";
		
//		String body = "<html>		<body bgcolor=\"#FFFFFF\"><br />		<h1><center><a target=\"_blank\" href=\"http://img.dmacareanaalefuncionanamelamance.ro/fdd4b2ad8e8be35868f26a1dec1257713b32f3983a7de1d7d632bdd75e3aafc5af9d256510a4347ad355024c50a07d2f\"><font color=\"#FF0000\"></font></a></center></h1><br />		<map name=\"mtpcc\"><area shape=\"rect\" coords=\"2,3,2717,2260\" target=\"_blank\" href=\"http://img.dmacareanaalefuncionanamelamance.ro/fdd4b2ad8e8be35868f26a1dec1257713b32f3983a7de1d7d632bdd75e3aafc5af9d256510a4347ad355024c50a07d2f\"></map>		<map name=\"kufps\"><area shape=\"rect\" coords=\"4,4,2075,2916\" target=\"_blank\" href=\"http://img.dmacareanaalefuncionanamelamance.ro/d3fdddbb5cbf0ce60060a61c453b9df16f45626f816eff3d3d44e8892f984a970a3cc682a71720fcc8ddcb310a354f79\"></map>		<table height=\"374\" width=\"457\" align=\"center\" border=\"0\" bgcolor=\"#2E9AFE\" cellspacing=\"0\" cellpadding=\"0\">		<tr><td bgcolor=\"#FFFFFF\" align=\"center\" ><p>Please click the \"Show Images\" button above if you cannot see the content.</p></td></tr>		<tr><td align=\"center\"><img style=\"display:block\" alt=\"content\" title=\"content\" src=\"http://img.dmacareanaalefuncionanamelamance.ro/d0a45b2aad159559871942c9ba2c4f41e42946e8b275d9ec4e98f40f15209fac64925dddeae59e5643dfbdef81fcbbe9\" usemap=\"#mtpcc\"></td></tr>		<tr><td align=\"center\"><img style=\"display:block\" alt=\"optout\" title=\"optout\" src=\"http://img.dmacareanaalefuncionanamelamance.ro/07a642d9a3eebfea354581f260fbc61ff2b450c60c899302ffac018d981dcf15591107fb1d673632501aeed4d0361755\" usemap=\"#kufps\"></td></tr></table><br />		</body>		</html>";		

//		String body = "<html><body>Hello World</body></html>";
		String body = "<!doctype html>"
+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">"
+ "    <head>"
+ "    </head><head>"
+ "    	<!-- NAME: BANNERS -->"
+ "        <!--[if gte mso 15]>"
+ "		<xml>"
+ "			<o:OfficeDocumentSettings>"
+ "			<o:AllowPNG/>"
+ "			<o:PixelsPerInch>96</o:PixelsPerInch>"
+ "			</o:OfficeDocumentSettings>"
+ "		</xml>"
+ "		<![endif]-->"
+ "		<meta charset=\"UTF-8\">"
+ "        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
+ "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
+ "		<title>*|MC:SUBJECT|*</title>"
+ "        "
+ "    <style type=\"text/css\">"
+ "		p{"
+ "			margin:10px 0;"
+ "			padding:0;"
+ "		}"
+ "		table{"
+ "			border-collapse:collapse;"
+ "		}"
+ "		h1,h2,h3,h4,h5,h6{"
+ "			display:block;"
+ "			margin:0;"
+ "			padding:0;"
+ "		}"
+ "		img,a img{"
+ "			border:0;"
+ "			height:auto;"
+ "			outline:none;"
+ "			text-decoration:none;"
+ "		}"
+ "		body,#bodyTable,#bodyCell{"
+ "			height:100%;"
+ "			margin:0;"
+ "			padding:0;"
+ "			width:100%;"
+ "		}"
+ "		#outlook a{"
+ "			padding:0;"
+ "		}"
+ "		img{"
+ "			-ms-interpolation-mode:bicubic;"
+ "		}"
+ "		table{"
+ "			mso-table-lspace:0pt;"
+ "			mso-table-rspace:0pt;"
+ "		}"
+ "		.ReadMsgBody{"
+ "			width:100%;"
+ "		}"
+ "		.ExternalClass{"
+ "			width:100%;"
+ "		}"
+ "		p,a,li,td,blockquote{"
+ "			mso-line-height-rule:exactly;"
+ "		}"
+ "		a[href^=tel],a[href^=sms]{"
+ "			color:inherit;"
+ "			cursor:default;"
+ "			text-decoration:none;"
+ "		}"
+ "		p,a,li,td,body,table,blockquote{"
+ "			-ms-text-size-adjust:100%;"
+ "			-webkit-text-size-adjust:100%;"
+ "		}"
+ "		.ExternalClass,.ExternalClass p,.ExternalClass td,.ExternalClass div,.ExternalClass span,.ExternalClass font{"
+ "			line-height:100%;"
+ "		}"
+ "		a[x-apple-data-detectors]{"
+ "			color:inherit !important;"
+ "			text-decoration:none !important;"
+ "			font-size:inherit !important;"
+ "			font-family:inherit !important;"
+ "			font-weight:inherit !important;"
+ "			line-height:inherit !important;"
+ "		}"
+ "		a.mcnButton{"
+ "			display:block;"
+ "		}"
+ "		.mcnImage{"
+ "			vertical-align:bottom;"
+ "		}"
+ "		.mcnTextContent{"
+ "			word-break:break-word;"
+ "		}"
+ "		.mcnTextContent img{"
+ "			height:auto !important;"
+ "		}"
+ "		.mcnDividerBlock{"
+ "			table-layout:fixed !important;"
+ "		}"
+ "		body,#bodyTable{"
+ "			background-color:#FFFFFF;"
+ "		}"
+ "		#bodyCell{"
+ "			border-top:0;"
+ "		}"
+ "		h1{"
+ "			color:#202020 !important;"
+ "			font-family:Helvetica;"
+ "			font-size:40px;"
+ "			font-style:normal;"
+ "			font-weight:bold;"
+ "			line-height:125%;"
+ "			letter-spacing:5px;"
+ "			text-align:center;"
+ "		}"
+ "		h2{"
+ "			color:#202020 !important;"
+ "			font-family:Helvetica;"
+ "			font-size:26px;"
+ "			font-style:normal;"
+ "			font-weight:bold;"
+ "			line-height:125%;"
+ "			letter-spacing:1px;"
+ "			text-align:center;"
+ "		}"
+ "		h3{"
+ "			color:#202020 !important;"
+ "			font-family:Helvetica;"
+ "			font-size:22px;"
+ "			font-style:normal;"
+ "			font-weight:bold;"
+ "			line-height:125%;"
+ "			letter-spacing:1px;"
+ "			text-align:center;"
+ "		}"
+ "		h4{"
+ "			color:#202020 !important;"
+ "			font-family:Helvetica;"
+ "			font-size:18px;"
+ "			font-style:normal;"
+ "			font-weight:bold;"
+ "			line-height:125%;"
+ "			letter-spacing:1px;"
+ "			text-align:center;"
+ "		}"
+ "		#templatePreheader{"
+ "			background-color:#202020;"
+ "			border-top:0;"
+ "			border-bottom:0;"
+ "		}"
+ "		.preheaderContainer .mcnTextContent,.preheaderContainer .mcnTextContent p{"
+ "			color:#FFFFFF;"
+ "			font-family:Helvetica;"
+ "			font-size:10px;"
+ "			line-height:125%;"
+ "			text-align:left;"
+ "		}"
+ "		.preheaderContainer .mcnTextContent a{"
+ "			color:#FFFFFF;"
+ "			font-weight:normal;"
+ "			text-decoration:underline;"
+ "		}"
+ "		#templateHeader{"
+ "			background-color:#FFFFFF;"
+ "			border:2px solid #202020;"
+ "		}"
+ "		.headerContainer .mcnTextContent,.headerContainer .mcnTextContent p{"
+ "			color:#202020;"
+ "			font-family:Helvetica;"
+ "			font-size:18px;"
+ "			line-height:150%;"
+ "			text-align:left;"
+ "		}"
+ "		.headerContainer .mcnTextContent a{"
+ "			color:#A6D9E5;"
+ "			font-weight:normal;"
+ "			text-decoration:underline;"
+ "		}"
+ "		#templateUpperBanner{"
+ "			background-color:#FFFFFF;"
+ "			border:2px solid #202020;"
+ "		}"
+ "		.upperBannerContainer .mcnTextContent,.upperBannerContainer .mcnTextContent p{"
+ "			color:#202020;"
+ "			font-family:Helvetica;"
+ "			font-size:18px;"
+ "			line-height:150%;"
+ "			text-align:left;"
+ "		}"
+ "		.upperBannerContainer .mcnTextContent a{"
+ "			color:#A6D9E5;"
+ "			font-weight:normal;"
+ "			text-decoration:underline;"
+ "		}"
+ "		#templateBody{"
+ "			background-color:#FFFFFF;"
+ "			border:2px solid #202020;"
+ "		}"
+ "		.bodyContainer .mcnTextContent,.bodyContainer .mcnTextContent p{"
+ "			color:#404040;"
+ "			font-family:Helvetica;"
+ "			font-size:16px;"
+ "			line-height:150%;"
+ "			text-align:left;"
+ "		}"
+ "		.bodyContainer .mcnTextContent a{"
+ "			color:#3386B0;"
+ "			font-weight:normal;"
+ "			text-decoration:underline;"
+ "		}"
+ "		#templateLowerBanner{"
+ "			background-color:#FFFFFF;"
+ "			border:2px solid #202020;"
+ "		}"
+ "		.lowerBannerContainer .mcnTextContent,.lowerBannerContainer .mcnTextContent p{"
+ "			color:#202020;"
+ "			font-family:Helvetica;"
+ "			font-size:18px;"
+ "			line-height:150%;"
+ "			text-align:left;"
+ "		}"
+ "		.lowerBannerContainer .mcnTextContent a{"
+ "			color:#202020;"
+ "			font-weight:normal;"
+ "			text-decoration:underline;"
+ "		}"
+ "		#templateFooter{"
+ "			background-color:#FFFFFF;"
+ "			border:2px solid #202020;"
+ "		}"
+ "		.footerContainer .mcnTextContent,.footerContainer .mcnTextContent p{"
+ "			color:#202020;"
+ "			font-family:Helvetica;"
+ "			font-size:10px;"
+ "			line-height:125%;"
+ "			text-align:center;"
+ "		}"
+ "		.footerContainer .mcnTextContent a{"
+ "			color:#202020;"
+ "			font-weight:normal;"
+ "			text-decoration:underline;"
+ "		"
+ "	@media only screen and (max-width: 480px){"
+ "		body,table,td,p,a,li,blockquote{"
+ "			-webkit-text-size-adjust:none !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		body{"
+ "			width:100% !important;"
+ "			min-width:100% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		#templatePreheader,#templateHeader,#templateBody,#templateFooter,.flexibleContainer,.flexibleWideContainer,#templateUpperBanner,#templateLowerBanner{"
+ "			max-width:600px !important;"
+ "			width:100% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnImage{"
+ "			width:100% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnShareContent,.mcnCaptionTopContent,.mcnCaptionBottomContent,.mcnTextContentContainer,.mcnBoxedTextContentContainer,.mcnImageGroupContentContainer,.mcnCaptionLeftTextContentContainer,.mcnCaptionRightTextContentContainer,.mcnCaptionLeftImageContentContainer,.mcnCaptionRightImageContentContainer,.mcnImageCardLeftTextContentContainer,.mcnImageCardRightTextContentContainer{"
+ "			max-width:100% !important;"
+ "			width:100% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnBoxedTextContentContainer{"
+ "			min-width:100% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnImageGroupContent{"
+ "			padding:9px !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnCaptionLeftContentOuter .mcnTextContent,.mcnCaptionRightContentOuter .mcnTextContent{"
+ "			padding-top:9px !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnImageCardTopImageContent,.mcnCaptionBlockInner .mcnCaptionTopContent:last-child .mcnTextContent{"
+ "			padding-top:18px !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnImageCardBottomImageContent{"
+ "			padding-bottom:9px !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnImageGroupBlockInner{"
+ "			padding-top:0 !important;"
+ "			padding-bottom:0 !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnImageGroupBlockOuter{"
+ "			padding-top:9px !important;"
+ "			padding-bottom:9px !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnTextContent,.mcnBoxedTextContentColumn{"
+ "			padding-right:18px !important;"
+ "			padding-left:18px !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnImageCardLeftImageContent,.mcnImageCardRightImageContent{"
+ "			padding-right:18px !important;"
+ "			padding-bottom:0 !important;"
+ "			padding-left:18px !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcpreview-image-uploader{"
+ "			display:none !important;"
+ "			width:100% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		h1{"
+ "			font-size:24px !important;"
+ "			line-height:125% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		h2{"
+ "			font-size:20px !important;"
+ "			line-height:125% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		h3{"
+ "			font-size:18px !important;"
+ "			line-height:125% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		h4{"
+ "			font-size:16px !important;"
+ "			line-height:125% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.mcnBoxedTextContentContainer .mcnTextContent,.mcnBoxedTextContentContainer .mcnTextContent p{"
+ "			font-size:18px !important;"
+ "			line-height:125% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		#templatePreheader{"
+ "			display:block !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.preheaderContainer .mcnTextContent,.preheaderContainer .mcnTextContent p{"
+ "			font-size:14px !important;"
+ "			line-height:115% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.headerContainer .mcnTextContent,.headerContainer .mcnTextContent p{"
+ "			font-size:18px !important;"
+ "			line-height:125% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.bodyContainer .mcnTextContent,.bodyContainer .mcnTextContent p{"
+ "			font-size:18px !important;"
+ "			line-height:125% !important;"
+ "		}"
+ ""
+ "}	@media only screen and (max-width: 480px){"
+ "		.footerContainer .mcnTextContent,.footerContainer .mcnTextContent p{"
+ "			font-size:14px !important;"
+ "			line-height:115% !important;"
+ "		}"
+ ""
+ "}</style></head>"
+ "    <body leftmargin=\"0\" marginwidth=\"0\" topmargin=\"0\" marginheight=\"0\" offset=\"0\" style=\"height: 100%;margin: 0;padding: 0;width: 100%;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #FFFFFF;\">"
+ "<center>"
+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"bodyTable\" style=\"border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; height: 100%; margin: 0; padding: 0; width: 100%; background-color: #ffffff;\">"
+ "<tbody>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" id=\"bodyCell\" style=\"padding-bottom: 40px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; height: 100%; margin: 0; padding: 0; width: 100%; border-top: 0;\"><!-- BEGIN TEMPLATE // -->"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse; width: 100%;\">"
+ "<tbody>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" style=\"padding-bottom: 18px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><!-- BEGIN PREHEADER // -->"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"templatePreheader\" style=\"border-collapse: collapse; border-top-width: 0px; border-bottom-width: 0px; width: 100%; background-color: #202020;\">"
+ "<tbody>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"flexibleContainer\" style=\"border-collapse: collapse; width: 600px;\">"
+ "<tbody>"
+ "<tr>"
+ "<td valign=\"top\" class=\"preheaderContainer\" style=\"padding-top: 9px; padding-bottom: 9px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<!-- // END PREHEADER --></td>"
+ "</tr>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" style=\"padding-bottom: 40px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"flexibleWideContainer\" style=\"border-collapse: collapse; width: 620px;\">"
+ "<tbody>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse; width: 100%;\">"
+ "<tbody>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse; width: 100%;\">"
+ "<tbody>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" style=\"padding-right: 10px; padding-left: 10px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><!-- BEGIN HEADER // -->"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"templateHeader\" style=\"border-collapse: collapse; border-top-width: 2px; border-right-width: 2px; border-left-width: 2px; border-top-style: solid; border-right-style: solid; border-left-style: solid; border-top-color: #202020; border-right-color: #202020; border-left-color: #202020; border-bottom-width: 0px !important; width: 580px; background-color: #ffffff;\">"
+ "<tbody>"
+ "<tr>"
+ "<td valign=\"top\" class=\"headerContainer\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnDividerBlock\" style=\"min-width: 100%; border-collapse: collapse; table-layout: fixed !important; width: 100%;\">"
+ "<tbody class=\"mcnDividerBlockOuter\">"
+ "<tr>"
+ "<td class=\"mcnDividerBlockInner\" style=\"min-width: 100%; padding: 18px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table class=\"mcnDividerContent\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"min-width: 100%; border-top-width: 0px; border-collapse: collapse; width: 100%;\">"
+ "<tbody>"
+ "<tr>"
+ "<td style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><span></span></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<!--            "
+ "                <td class=\"mcnDividerBlockInner\" style=\"padding: 18px;\">"
+ "                <hr class=\"mcnDividerContent\" style=\"border-bottom-color:none; border-left-color:none; border-right-color:none; border-bottom-width:0; border-left-width:0; border-right-width:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0;\" />"
+ "--></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<!-- // END HEADER --></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "<tr>"
+ "<td align=\"center\" valign=\"bottom\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse; width: 100%;\">"
+ "<tbody>"
+ "<tr>"
+ "<td align=\"center\" valign=\"bottom\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><!-- BEGIN UPPER BANNER // -->"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"templateUpperBanner\" style=\"border-collapse: collapse; border: 2px solid #202020; width: 600px; background-color: #ffffff;\">"
+ "<tbody>"
+ "<tr>"
+ "<td valign=\"top\" class=\"upperBannerContainer\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnImageBlock\" style=\"min-width: 100%; border-collapse: collapse; width: 100%;\">"
+ "<tbody class=\"mcnImageBlockOuter\">"
+ "<tr>"
+ "<td valign=\"top\" style=\"padding: 9px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\" class=\"mcnImageBlockInner\">"
+ "<table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnImageContentContainer\" style=\"min-width: 100%; border-collapse: collapse; width: 100%;\">"
+ "<tbody>"
+ "<tr>"
+ "<td class=\"mcnImageContent\" valign=\"top\" style=\"padding-right: 9px; padding-left: 9px; padding-top: 0; padding-bottom: 0; text-align: center; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><a href=\"http://thecoolinfo.com/\" title=\"\" target=\"_blank\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"> <img align=\"center\" alt=\"\" src=\"https://gallery.mailchimp.com/77735ecefd1bde96091f39e21/images/5a55e236-6743-4cac-a99e-0b9edc04781c.png\" width=\"230\" style=\"max-width: 230px; padding-bottom: 0; display: inline !important; vertical-align: bottom; border: 0; height: auto; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic;\" class=\"mcnImage\" /> </a></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<!-- // END UPPER BANNER --></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"flexibleWideContainer\" style=\"border-collapse: collapse; width: 600px;\">"
+ "<tbody>"
+ "<tr>"
+ "<td align=\"right\" valign=\"top\" width=\"10\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><img src=\"http://gallery.mailchimp.com/27aac8a65e64c994c4416d6b8/images/bstl.png\" height=\"10\" width=\"10\" style=\"display: block; border: 0; height: auto; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic;\" /></td>"
+ "<td align=\"center\" rowspan=\"2\" valign=\"top\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse; width: 100%;\">"
+ "<tbody>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><!-- BEGIN BODY // -->"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"templateBody\" style=\"border-collapse: collapse; border: 2px solid #202020; width: 580px; background-color: #ffffff;\">"
+ "<tbody>"
+ "<tr>"
+ "<td valign=\"top\" class=\"bodyContainer\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnDividerBlock\" style=\"min-width: 100%; border-collapse: collapse; table-layout: fixed !important; width: 100%;\">"
+ "<tbody class=\"mcnDividerBlockOuter\">"
+ "<tr>"
+ "<td class=\"mcnDividerBlockInner\" style=\"min-width: 100%; padding: 18px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table class=\"mcnDividerContent\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"min-width: 100%; border-top-width: 0px; border-collapse: collapse; width: 100%;\">"
+ "<tbody>"
+ "<tr>"
+ "<td style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><span></span></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<!--            "
+ "                <td class=\"mcnDividerBlockInner\" style=\"padding: 18px;\">"
+ "                <hr class=\"mcnDividerContent\" style=\"border-bottom-color:none; border-left-color:none; border-right-color:none; border-bottom-width:0; border-left-width:0; border-right-width:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0;\" />"
+ "--></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnTextBlock\" style=\"border-collapse: collapse; width: 100%;\">"
+ "<tbody class=\"mcnTextBlockOuter\">"
+ "<tr>"
+ "<td valign=\"top\" class=\"mcnTextBlockInner\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnTextContentContainer\" style=\"border-collapse: collapse; width: 578px;\">"
+ "<tbody>"
+ "<tr>"
+ "<td valign=\"top\" class=\"mcnTextContent\" style=\"padding: 9px 18px; line-height: normal; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; word-break: break-word; color: #404040; font-family: Helvetica; font-size: 16px; text-align: left;\">"
+ "<h3 style=\"display: block; margin: 0; padding: 0; font-family: Helvetica; font-size: 22px; font-style: normal; font-weight: bold; line-height: 125%; letter-spacing: 1px; text-align: center; color: #202020 !important;\">Obama: No comment on Clinton and trade &mdash; and other 2016 issues</h3>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnCaptionBlock\" style=\"border-collapse: collapse; width: 100%;\">"
+ "<tbody class=\"mcnCaptionBlockOuter\">"
+ "<tr>"
+ "<td class=\"mcnCaptionBlockInner\" valign=\"top\" style=\"padding: 9px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnCaptionBottomContent\" style=\"border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<tbody>"
+ "<tr>"
+ "<td class=\"mcnCaptionBottomImageContent\" align=\"center\" valign=\"top\" style=\"padding: 0 9px 9px 9px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><a href=\"http://onpolitics.usatoday.com/2015/10/16/obama-2016-candidates-democrats/\" title=\"\" target=\"_blank\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"> <img alt=\"\" src=\"https://gallery.mailchimp.com/77735ecefd1bde96091f39e21/images/3bf54ea5-6587-4f6f-8e5c-a0a9acf91138.jpg\" width=\"300\" style=\"max-width: 300px; border: 0; height: auto; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; vertical-align: bottom;\" class=\"mcnImage\" /> </a></td>"
+ "</tr>"
+ "<tr>"
+ "<td class=\"mcnTextContent\" valign=\"top\" style=\"padding: 0px 9px; line-height: normal; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; word-break: break-word; color: #404040; font-family: Helvetica; font-size: 16px; text-align: left;\" width=\"542\">"
+ "<p style=\"border: 0px; font-family: Merriweather, 'Times New Roman', Times, serif; font-size: 14px; outline: 0px; padding: 0px; vertical-align: baseline; margin-bottom: 1.5em; cursor: text; font-stretch: normal; line-height: normal; margin: 10px 0; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #404040; text-align: left;\">In declining to discuss Hillary Clinton&rsquo;s newfound opposition to the Pacific Rim free trade deal, President Obama served notice Friday: He won&rsquo;t be commenting on lots of things Democratic candidates say during the 2016 election.</p>"
+ "<p style=\"border: 0px; font-family: Merriweather, 'Times New Roman', Times, serif; font-size: 14px; outline: 0px; padding: 0px; vertical-align: baseline; margin-bottom: 1.5em; cursor: text; font-stretch: normal; line-height: normal; margin: 10px 0; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #404040; text-align: left;\">&ldquo;I mean, here is a general proposition, guys,&rdquo; Obama told reporters. &ldquo;During the course of what will be a long campaign, I probably won&rsquo;t be commenting on every single utterance or decision that the various candidates make.&rdquo;</p>"
+ "<p style=\"border: 0px; font-family: Merriweather, 'Times New Roman', Times, serif; font-size: 14px; outline: 0px; padding: 0px; vertical-align: baseline; margin-bottom: 1.5em; cursor: text; font-stretch: normal; line-height: normal; margin: 10px 0; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #404040; text-align: left;\">The reason, he said: &ldquo;I think that it is natural and proper for candidates to run on their own vision and their own platform.&rdquo;</p>"
+ "<p style=\"border: 0px; font-family: Merriweather, 'Times New Roman', Times, serif; font-size: 14px; outline: 0px; padding: 0px; vertical-align: baseline; margin-bottom: 1.5em; cursor: text; font-stretch: normal; line-height: normal; margin: 10px 0; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #404040; text-align: left;\">Asked specifically about Clinton&rsquo;s coming out against the Trans-Pacific Partnership, Obama said that, &ldquo;with&nbsp;respect to the trade and how Hillary views trade, I would have you direct questions to her.&rdquo;</p>"
+ "<p style=\"border: 0px; font-family: Merriweather, 'Times New Roman', Times, serif; font-size: 14px; outline: 0px; padding: 0px; vertical-align: baseline; margin-bottom: 1.5em; cursor: text; font-stretch: normal; line-height: normal; margin: 10px 0; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #404040; text-align: left;\">Obama himself did&nbsp;talk up the Trans-Pacific Partnership, saying the free-trade deal will benefit U.S. workers.</p>"
+ "<p style=\"border: 0px; font-family: Merriweather, 'Times New Roman', Times, serif; font-size: 14px; outline: 0px; padding: 0px; vertical-align: baseline; margin-bottom: 1.5em; cursor: text; font-stretch: normal; line-height: normal; margin: 10px 0; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #404040; text-align: left;\">Speaking at a joint news conference with South Korean President Park Geun-hye, Obama did say that he and the Democratic presidential candidates &ldquo;agree on 95% of stuff.&rdquo;</p>"
+ "<p style=\"border: 0px; font-family: Merriweather, 'Times New Roman', Times, serif; font-size: 14px; outline: 0px; padding: 0px; vertical-align: baseline; margin-bottom: 1.5em; cursor: text; font-stretch: normal; line-height: normal; margin: 10px 0; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #404040; text-align: left;\">While &ldquo;there are going to be areas where they differ at any given point,&rdquo; Obama indicated he wouldn&rsquo;t be discussing them &mdash; though it seems certain he won&rsquo;t be so reticent when it comes to his differences with the Republicans.</p>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<!-- // END BODY --></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "<td align=\"left\" valign=\"top\" width=\"10\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><img src=\"http://gallery.mailchimp.com/27aac8a65e64c994c4416d6b8/images/bstr.png\" height=\"10\" width=\"10\" style=\"display: block; border: 0; height: auto; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic;\" /></td>"
+ "</tr>"
+ "<tr>"
+ "<td align=\"right\" valign=\"bottom\" width=\"10\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><img src=\"http://gallery.mailchimp.com/27aac8a65e64c994c4416d6b8/images/bsbl.png\" height=\"10\" width=\"10\" style=\"display: block; border: 0; height: auto; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic;\" /></td>"
+ "<td align=\"left\" valign=\"bottom\" width=\"10\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><img src=\"http://gallery.mailchimp.com/27aac8a65e64c994c4416d6b8/images/bsbr.png\" height=\"10\" width=\"10\" style=\"display: block; border: 0; height: auto; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic;\" /></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><!-- BEGIN LOWER BANNER // -->"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"templateLowerBanner\" style=\"border-collapse: collapse; border: 2px solid #202020; width: 600px; background-color: #ffffff;\">"
+ "<tbody>"
+ "<tr>"
+ "<td valign=\"top\" class=\"lowerBannerContainer\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnDividerBlock\" style=\"min-width: 100%; border-collapse: collapse; table-layout: fixed !important; width: 100%;\">"
+ "<tbody class=\"mcnDividerBlockOuter\">"
+ "<tr>"
+ "<td class=\"mcnDividerBlockInner\" style=\"min-width: 100%; padding: 18px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table class=\"mcnDividerContent\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"min-width: 100%; border-top-width: 0px; border-collapse: collapse; width: 100%;\">"
+ "<tbody>"
+ "<tr>"
+ "<td style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><span></span></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<!--            "
+ "                <td class=\"mcnDividerBlockInner\" style=\"padding: 18px;\">"
+ "                <hr class=\"mcnDividerContent\" style=\"border-bottom-color:none; border-left-color:none; border-right-color:none; border-bottom-width:0; border-left-width:0; border-right-width:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0;\" />"
+ "--></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<!-- // END LOWER BANNER --></td>"
+ "</tr>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse: collapse; width: 100%;\">"
+ "<tbody>"
+ "<tr>"
+ "<td align=\"center\" valign=\"top\" style=\"padding-right: 10px; padding-left: 10px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\"><!-- BEGIN FOOTER // -->"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"templateFooter\" style=\"border-collapse: collapse; border-right-width: 2px; border-bottom-width: 2px; border-left-width: 2px; border-right-style: solid; border-bottom-style: solid; border-left-style: solid; border-right-color: #202020; border-bottom-color: #202020; border-left-color: #202020; border-top-width: 0px !important; width: 580px; background-color: #ffffff;\">"
+ "<tbody>"
+ "<tr>"
+ "<td valign=\"top\" class=\"footerContainer\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnTextBlock\" style=\"border-collapse: collapse; width: 100%;\">"
+ "<tbody class=\"mcnTextBlockOuter\">"
+ "<tr>"
+ "<td valign=\"top\" class=\"mcnTextBlockInner\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">"
+ "<table align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"mcnTextContentContainer\" style=\"border-collapse: collapse; width: 578px;\">"
+ "<tbody>"
+ "<tr>"
+ "<td valign=\"top\" class=\"mcnTextContent\" style=\"padding: 9px 18px; line-height: normal; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; word-break: break-word; color: #202020; font-family: Helvetica; font-size: 10px; text-align: center;\"><em>Copyright 2015 The Cool Info, All rights reserved.</em><br /> <br /> Want to change how you receive these emails?<br /> You can <a href=\"*|UPDATE_PROFILE|*\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #202020; font-weight: normal; text-decoration: underline;\">c</a><a href=\"http://thecoolinfo.com/contact.html\" target=\"_blank\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #202020; font-weight: normal; text-decoration: underline;\">ontact us</a> or <a href=\"%%unsubscribelink%%\" style=\"mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; color: #202020; font-weight: normal; text-decoration: underline;\">unsubscribe from this list</a></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<!-- // END FOOTER --></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "<!-- // END TEMPLATE --></td>"
+ "</tr>"
+ "</tbody>"
+ "</table>"
+ "</center>"
+ "</body>"
+ "</html>";

		if (test) {
			/*
			 * THIS IS ONLY FOR TEST
			 */
			// WolfYahoo handler = new TestWolfYahoo();
			// handler.generateAndSendMail(users[WolfYahoo.randInt(0,
			// users.length-1)], pass, offerFroms[WolfYahoo.randInt(0,
			// offerFroms.length-1)], to, subjects[WolfYahoo.randInt(0,
			// subjects.length-1)], body);
		} else {
			/*
			 * THIS IS PRODUCTION
			 */
			WolfYahoo handler = new ProductionWolfYahoo();
			try {
				logger.info("customer: " + contactEmail + " sender: " + senderEmail);
				handler.generateAndSendMail(senderEmail, senderPassword, subjects[WolfYahoo.randInt(0, subjects.length - 1)], body, contactEmail, senderDomainRo, offerFroms[WolfYahoo.randInt(0, offerFroms.length - 1)]);

			} catch (Exception e) {
				logger.info("Error", e.getMessage());
				return;
			}
		}
	}
}
